//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsWorkingDay
    {
        public int Id { get; set; }
        public int DoctorID { get; set; }
        public int WeekID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Weekday Weekday { get; set; }
    }
}
